/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ArrowDown: typeof import('./src/components/Icon/ArrowDown.vue')['default']
    ArrowRight: typeof import('./src/components/Icon/ArrowRight.vue')['default']
    CareerBenefit: typeof import('./src/components/section/CareerBenefit.vue')['default']
    CareerBenefitCard: typeof import('./src/components/common/CareerBenefitCard.vue')['default']
    CareerScroll: typeof import('./src/components/section/CareerScroll.vue')['default']
    CareerSlider: typeof import('./src/components/common/CareerSlider.vue')['default']
    Check: typeof import('./src/components/Icon/Check.vue')['default']
    Close: typeof import('./src/components/Icon/Close.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GameCard: typeof import('./src/components/GameCard.vue')['default']
    GameList: typeof import('./src/components/GameList.vue')['default']
    GoTop: typeof import('./src/components/GoTop.vue')['default']
    Hamburger: typeof import('./src/components/common/Hamburger.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HeaderMobile: typeof import('./src/components/HeaderMobile.vue')['default']
    HomeAbout: typeof import('./src/components/section/HomeAbout.vue')['default']
    HomeAboutTri: typeof import('./src/components/section/HomeAboutTri.vue')['default']
    HomeBanner: typeof import('./src/components/section/HomeBanner.vue')['default']
    HomeCardList: typeof import('./src/components/HomeCardList.vue')['default']
    HomeService: typeof import('./src/components/section/HomeService.vue')['default']
    IconArrowRight: typeof import('./src/components/Icon/IconArrowRight.vue')['default']
    IconCigarette: typeof import('./src/components/Icon/IconCigarette.vue')['default']
    IconClear: typeof import('./src/components/Icon/IconClear.vue')['default']
    IconEdit: typeof import('./src/components/Icon/IconEdit.vue')['default']
    IconEmail: typeof import('./src/components/Icon/IconEmail.vue')['default']
    IconFace: typeof import('./src/components/Icon/IconFace.vue')['default']
    IconGeo: typeof import('./src/components/Icon/IconGeo.vue')['default']
    IconHot: typeof import('./src/components/Icon/IconHot.vue')['default']
    IconLoading: typeof import('./src/components/Icon/IconLoading.vue')['default']
    IconLogo: typeof import('./src/components/Icon/IconLogo.vue')['default']
    IconLogoBlack: typeof import('./src/components/Icon/IconLogoBlack.vue')['default']
    IconLogoUni: typeof import('./src/components/Icon/IconLogoUni.vue')['default']
    IconLoved: typeof import('./src/components/Icon/IconLoved.vue')['default']
    IconNotice: typeof import('./src/components/Icon/IconNotice.vue')['default']
    IconPhone: typeof import('./src/components/Icon/IconPhone.vue')['default']
    IconSearch: typeof import('./src/components/Icon/IconSearch.vue')['default']
    IconShare: typeof import('./src/components/Icon/IconShare.vue')['default']
    IconSwitch: typeof import('./src/components/Icon/IconSwitch.vue')['default']
    IconUndo: typeof import('./src/components/Icon/IconUndo.vue')['default']
    IconUnLove: typeof import('./src/components/Icon/IconUnLove.vue')['default']
    Landing: typeof import('./src/components/common/Landing.vue')['default']
    LazyImg: typeof import('./src/components/common/LazyImg.vue')['default']
    NumberList: typeof import('./src/components/common/NumberList.vue')['default']
    Popup: typeof import('./src/components/common/Popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/Search.vue')['default']
    Slider: typeof import('./src/components/common/Slider.vue')['default']
  }
}
